# Generated by Django 4.2 on 2025-11-22 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('HIGIENE', 'Higiene y Cuidado del Bebé'), ('ALIMENTACION', 'Alimentación y Accesorios')], default='HIGIENE', max_length=20)),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('variacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'unique_together': {('nombre', 'variacion')},
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.producto')),
            ],
        ),
    ]
