"""
Django settings for panalera_project project.

Generated by 'django-admin startproject' using Django 4.2.
"""

from pathlib import Path
import os 
from dotenv import load_dotenv # 1. Importar dotenv

# Carga las variables de entorno del archivo .env
# Esto es CRÍTICO para la seguridad
load_dotenv() 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================
# CONFIGURACIÓN GENERAL (CORRECCIÓN DE SEGURIDAD)
# ============================

# 2. Cargar SECRET_KEY desde las variables de entorno
# Si la clave no existe, el programa fallará, lo cual es más seguro que usar una clave pública.
SECRET_KEY = os.getenv('SECRET_KEY')

# 3. Cargar DEBUG desde las variables de entorno (convirtiendo el string a booleano)
# Por defecto, si no encuentra la variable, asume False.
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# 4. Cargar ALLOWED_HOSTS desde las variables de entorno
# Convierte la cadena de hosts (separados por comas) en una lista de Python.
allowed_hosts_str = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_str.split(',') if host.strip()]


# ============================
# APLICACIONES INSTALADAS
# ============================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Tus apps
    'usuarios',
    'inventario',

    'widget_tweaks',
]


# ============================
# MIDDLEWARE
# ============================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'panalera_project.urls'


# ============================
# TEMPLATES
# ============================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],     
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'panalera_project.wsgi.application'


# ============================
# BASE DE DATOS
# ============================

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ============================
# VALIDACIONES DE CONTRASEÑA
# ============================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ============================
# INTERNACIONALIZACIÓN
# ============================

LANGUAGE_CODE = 'es-latam'
TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True


# ============================
# ARCHIVOS ESTÁTICOS
# ============================

STATIC_URL = 'static/'


# ============================
# ARCHIVOS MEDIA (IMÁGENES Y ARCHIVOS SUBIDOS)
# ============================

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ============================
# CONFIGURACIÓN POR DEFECTO
# ============================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
